defaults:
  - stellar
  - override datamodule: image_folder
  - _self_
job_name: smoke
model:
  vit_pretrained: null
  vit_config:
    hidden_size: 48
    num_hidden_layers: 1
    num_attention_heads: 4
    intermediate_size: 96
  num_sparse_tokens: 4
  num_clusters: 16
  prototype_dim: 16
  do_recon: False
  vq_model: null
  num_masks: 2
  num_local_crops: 2
  momentum_teacher: True
  teacher_momentum_final: 1.0
trainer:
  accelerator: cpu
  devices: 1
  strategy: auto
  precision: 32-true
  max_steps: 2
  max_epochs: 1
  limit_val_batches: 1
  num_sanity_val_steps: 0
  enable_progress_bar: False
datamodule:
  dataloaders:
    train:
      batch_size: 2
      num_workers: 0
      prefetch_factor: null
    validate:
      batch_size: 2
      num_workers: 0
    test:
      batch_size: 2
      num_workers: 0